name: Links Checker

on:
  workflow_dispatch:
  schedule:
      - cron: "0 0 * * 0" # weekly run

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.8.0

      - name: Check for Errors
        run: |
          if [ ${{ steps.lychee.outputs.exit_code }} -ne 0 ]; then
            echo "Link Checker encountered errors."
            cat ./lychee/out.md  # Print the detailed error report
            # Add additional error details if needed
          fi

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue, good first issue
